use_frameworks!

target 'MTCoordinatorView_Example' do
  pod 'MTCoordinatorView', :path => '../'

  target 'MTCoordinatorView_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
